# Generated by Django 3.1 on 2020-08-07 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(choices=[('INC', 'Income'), ('EXP', 'Expense')], default='INC', max_length=3)),
                ('Description', models.TextField(max_length=50)),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
