# Generated by Django 3.1 on 2020-08-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetitem',
            name='Description',
            field=models.CharField(max_length=50),
        ),
    ]
