# Generated by Django 3.1 on 2020-08-07 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0002_auto_20200807_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budgetitem',
            name='Amount',
        ),
        migrations.CreateModel(
            name='BudgetRecord',
            fields=[
                ('budgetitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='budget.budgetitem')),
                ('Amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Date', models.DateTimeField(auto_now_add=True)),
            ],
            bases=('budget.budgetitem',),
        ),
    ]
